### ISSUE TITLE
Chart data  has come but not showing in browser

### ISSUE THREAD

**Issue by illusion199** [LaravelDaily/laravel-charts#9] opened 2019-06-21 19:45 UTC
Like this.
http://prntscr.com/o50nxi

**Comment by PovilasKorop** [comment] 2019-06-22 06:07
@illusion199 very weird. Could you upload your full project source code (or maybe just HTML) somewhere and send me the link? I would download and debug.

Without full source code, I can't really help you.

**Comment by datomnurdin** [comment] 2019-11-05 12:11
@illusion199 @PovilasKorop any update so far?

**Comment by PovilasKorop** [comment] 2019-11-05 13:19
Haven't received the code from issue author, so can't help.

**Comment by anjan12pandey** [comment] 2020-02-14 09:46
I'm using laravel 6 and facing the same problem, Data coming but not showing on the browser.

[chart-testing.zip](https://github.com/LaravelDaily/laravel-charts/files/4203833/chart-testing.zip)

**Comment by PovilasKorop** [comment] 2020-05-11 13:47
@anjan12pandey sorry just now saw the issues, not sure why didn't receive notifications about them earlier. Downloaded the code you added, but it doesn't have the Views code, and quite likely the error is somewhere on that side, not in Controller.

So have you solved that problem three months ago? Is it still relevant? If you don't reply within 14 days, will close the issue as "cannot reproduce".

**Closed** 2020-06-06 05:18 UTC
